[bumpver]
current_version = "0.2.3"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "v{new_version}"
tag_scope = "default"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"bumpver.toml" = ['current_version = "{version}"']
"package.json" = ['"version": "{version}"']
